#!/bin/bash
#After ssh vpn has been established by remote run this script here on
#the local computer.
sudo ip route add 192.168.0.0/24 dev ppp0
sudo iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
